name: Build & Publish (Electron Forge)

on:
  push:
    tags:
      - "v*.*.*" # only publish on version tags like v1.2.3

jobs:
  forge-publish:
    name: Forge publish (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      # Needed by @electron-forge/publisher-github
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only used on mac (notarization)
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}   # app-specific password
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Install deps
        run: npm ci

      # Optional: if you have a separate web build step in package.json
      - name: Build (optional)
        run: npm run build --if-present

      # Publish with Electron Forge (reads forge.config.*)
      - name: Electron Forge publish
        run: npx electron-forge publish --ci
