name: Build & Publish (Electron Forge)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  make:
    name: Make (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Apple creds are optional. If absent, mac signing/notarize is skipped by forge.config.js gating.
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm
      - run: npm ci
      - name: Forge make & publish
        run: npm run publish
