name: Build/release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Build/release Electron app
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          package_root: '.'
          build_script_name: 'build'
          # macOS code signing (optional)
          apple_id: ${{ secrets.APPLE_ID }}
          apple_password: ${{ secrets.APPLE_PASSWORD }}
          apple_team_id: ${{ secrets.APPLE_TEAM_ID }}